### ISSUE TITLE
absolute url issue in deployment

### ISSUE THREAD

**Issue by thefeqy** [haruncpi/laravel-simple-filemanager#5]
I have a problem that all files are working in my local environment, but when I deploy the project no file works,
the cause of the problem that the package store the full path of the file including the base URL.
so why not only store the file path without the base URL, or to give me the option to choose between including the base URL or not.
thank you

**Comment by haruncpi** [comment]
If you developed the entire application in local and all file/image path with local absolute path then simply you can follow the steps.

- Export the SQL file from local
- Open SQL file in a notepad, now search and replace all the local absolute paths with remote.
Ex: http://localhost:8000 -> http://example.com
- Save the SQL file.
- Now upload the SQL to remote.

**Comment by thefeqy** [comment]
sorry but I'm using sqlite3, so I can't open the DB file and edit it, so this solution is not compatible with me

**Comment by haruncpi** [comment]
You can use SQL `replace` function before export from local where you need. 
```
update table_name set content_url = replace(content_url, 'http://localhost:8000', 'http://example.com')
